// new-tauri-app/src/widgets/sidebar/sidebar-item.tsx
import { Icon } from 'solid-heroicons'
import { photo } from 'solid-heroicons/outline'
import { Component } from 'solid-js'

import { type ImageRecord } from '~/shared/db'
import { selectedRecord, setSelectedRecord } from '~/shared/store'
import { Button } from '~/shared/ui/button'

type SidebarItemProps = {
  item: ImageRecord
}

const SidebarItem: Component<SidebarItemProps> = (props) => {
  return (
    <Button
      variant={
        selectedRecord() && selectedRecord()?.id === props.item.id
          ? 'secondary'
          : 'outline'
      }
      class="h-8 justify-start px-3 shadow"
      onClick={() => {
        setSelectedRecord(props.item)
      }}
    >
      <Icon path={photo} class="mr-2 size-4 shrink-0" />
      <span class="truncate text-xs font-light">{props.item.name}</span>
    </Button>
  )
}

export default SidebarItem

// tauri-svelte-app/src/widgets/sidebar/sidebar-item.svelte
<script lang="ts">
  import { Button } from "@/shared/ui/button"
  import { selectedRecord } from '@/shared/stores/record-store';
  import { get } from "svelte/store"
  import { type ImageRecord } from "@/shared/db"
  import ImageIcon from "lucide-svelte/icons/image"

  export let item: ImageRecord;

  let isSelected = false;

  $: {
    const currentRecord = get(selectedRecord);
    isSelected = !!(currentRecord && currentRecord.id === item.id);
  }
</script>

<Button
  variant={isSelected ? 'secondary' : 'outline'}
  class="h-8 justify-start px-3 shadow"
  on:click={() => selectedRecord.set(item)}
>
  <ImageIcon class="mr-2 size-4 shrink-0" />
  <span class="truncate text-xs font-light">{item.name}</span>
</Button>
