// new-tauri-app/src/widgets/sidebar/sidebar.tsx
import { createDexieArrayQuery } from 'solid-dexie'
import { Icon } from 'solid-heroicons'
import { ellipsisHorizontal, plus } from 'solid-heroicons/outline'
import { type Component, For } from 'solid-js'

import BrowserFileButton from '~/features/browse-file/browse-file'
import { Logo } from '~/features/logo'
import { db, ImageRecord } from '~/shared/db'
import { searchString } from '~/shared/store/search-store'
import { Button } from '~/shared/ui/button'

import SidebarItem from './sidebar-item'
import SidebarSearch from './sidebar-search'

const SideBar: Component = () => {
  const records = createDexieArrayQuery(() =>
    db.records.toArray()
  ) as ImageRecord[]
  return (
    <div class="flex size-full flex-col gap-2 px-3">
      <div class="flex h-12 w-full shrink-0 items-center justify-between border-b">
        <Logo />
        <div class="flex items-center gap-1">
          <BrowserFileButton size="icon" variant="ghost" class="size-8">
            <Icon path={plus} class="size-5" />
          </BrowserFileButton>
          <Button size="icon" variant="ghost" class="size-8">
            <Icon path={ellipsisHorizontal} class="size-6" />
          </Button>
        </div>
      </div>
      <div class="my-1 flex h-10 w-full items-center">
        <SidebarSearch />
      </div>
      <ul class="flex size-full flex-col gap-2 overflow-y-auto overflow-x-hidden">
        <For
          each={records.filter((x: ImageRecord) => {
            const searchStr = searchString().toLowerCase()
            return !searchStr || x.name.toLowerCase().includes(searchStr)
          })}
        >
          {(item) => <SidebarItem item={item} />}
        </For>
      </ul>
    </div>
  )
}

export default SideBar

// tauri-svelte-app/src/widgets/sidebar/sidebar.svelte
<script lang="ts">
  import { Logo } from '@/features/logo'
  import { Button } from '@/shared/ui/button'
  import SidebarSearch from './sidebar-search.svelte'
  import EllipsisIcon from 'lucide-svelte/icons/ellipsis'
  import PlusIcon from 'lucide-svelte/icons/plus'
  import { liveQuery } from 'dexie'
  import { db, type ImageRecord } from '@/shared/db'
  import SidebarItem from './sidebar-item.svelte'
  import { BrowseButton } from '@/features/browse-button'
  import { searchString } from '@/shared/stores/search-store'

  let records: ImageRecord[] = []
  let filteredRecords: ImageRecord[] = []
  let searchName = ''

  liveQuery(() => db.records.toArray()).subscribe(
    (result) => (records = result)
  )

  searchString.subscribe(
    (value) => (searchName = value ? value.toLowerCase() : '')
  )

  $: filteredRecords = searchName
    ? records.filter((item) => item.name.toLowerCase().includes(searchName))
    : records
</script>

<div class="flex size-full flex-col gap-2 px-3">
  <div class="flex h-12 w-full shrink-0 items-center justify-between border-b">
    <Logo />
    <div class="flex items-center gap-1">
      <BrowseButton size="icon" variant="ghost" class="size-8">
        <PlusIcon class="size-[1.2rem]" />
      </BrowseButton>
      <Button size="icon" variant="ghost" class="size-8">
        <EllipsisIcon class="size-5" />
      </Button>
    </div>
  </div>
  <div class="my-1 flex h-10 w-full items-center">
    <SidebarSearch />
  </div>
  <ul class="flex size-full flex-col gap-2 overflow-y-auto overflow-x-hidden">
    {#if filteredRecords}
      {#each filteredRecords as item (item.id)}
        <SidebarItem {item} />
      {/each}
    {:else}
      <span>List is empty</span>
    {/if}
  </ul>
</div>
