// new-tauri-app/src/shared/ui/label.tsx
import type { Component, ComponentProps } from 'solid-js'
import { splitProps } from 'solid-js'

import { cn } from '~/shared/lib/utils'

const Label: Component<ComponentProps<'label'>> = (props) => {
  const [local, others] = splitProps(props, ['class'])
  return (
    <label
      class={cn(
        'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        local.class
      )}
      {...others}
    />
  )
}

export { Label }

// tauri-svelte-app/src/shared/ui/label/label.svelte
<script lang="ts">
  import { Label as LabelPrimitive } from 'bits-ui'
  import { cn } from '@/shared/libs'

  type $$Props = LabelPrimitive.Props
  type $$Events = LabelPrimitive.Events

  let className: $$Props['class'] = undefined
  export { className as class }
</script>

<LabelPrimitive.Root
  class={cn(
    'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
    className
  )}
  {...$$restProps}
  on:mousedown
>
  <slot />
</LabelPrimitive.Root>
