// apps/desktop/src/widgets/sidebar/sidebar.svelte
<script lang="ts">
  import { liveQuery } from 'dexie'
  import EllipsisIcon from 'lucide-svelte/icons/ellipsis'
  import PlusIcon from 'lucide-svelte/icons/plus'
  import TrashIcon from 'lucide-svelte/icons/trash'
  import { toast } from 'svelte-sonner'

  import { deleteAllRecords, type ImageRecord } from '@/entities/image-record'
  import { BrowseButton } from '@/features/browse-button'
  import { Logo } from '@/features/logo'
  import { db } from '@/shared/db'
  import { searchString } from '@/shared/stores/search-store'
  import { Button } from '@repo/ui/button'
  import * as DropdownMenu from '@repo/ui/dropdown-menu'
  import { ScrollArea } from '@repo/ui/scroll-area'

  import SidebarItem from './sidebar-item.svelte'
  import SidebarSearch from './sidebar-search.svelte'

  let records: ImageRecord[] = []
  let filteredRecords: ImageRecord[] = []
  let searchName: string = ''

  liveQuery(() => db.records.toArray()).subscribe(
    (result) => (records = result)
  )

  searchString.subscribe(
    (value) => (searchName = value ? value.toLowerCase() : '')
  )

  const onClearAction = async () => {
    try {
      await deleteAllRecords()
      toast.success('Successfully clear all records')
    } catch {
      toast.error('Error while deleting items')
    }
  }

  $: filteredRecords = searchName
    ? records.filter((item) => item.name.toLowerCase().includes(searchName))
    : records
</script>

<div class="flex size-full overflow-hidden flex-col gap-2">
  <div class="w-full px-3 shrink-0">
    <div class="flex h-12 w-full items-center justify-between border-b">
      <Logo />
      <div class="flex items-center gap-1">
        <BrowseButton size="icon" variant="ghost" class="size-8">
          <PlusIcon class="size-[1.2rem]" />
        </BrowseButton>
        <DropdownMenu.Root>
          <DropdownMenu.Trigger asChild let:builder>
            <Button
              builders={[builder]}
              size="icon"
              variant="ghost"
              class="size-8"
            >
              <EllipsisIcon class="size-5" />
            </Button>
          </DropdownMenu.Trigger>
          <DropdownMenu.Content>
            <DropdownMenu.Group>
              <DropdownMenu.Item on:click={onClearAction}>
                <TrashIcon class="size-4 mr-2" />
                Clear
              </DropdownMenu.Item>
            </DropdownMenu.Group>
          </DropdownMenu.Content>
        </DropdownMenu.Root>
      </div>
    </div>
  </div>

  <div class="my-1 flex shrink-0 h-10 w-full items-center px-3">
    <SidebarSearch />
  </div>
  <ScrollArea class="[&>div>div]:w-full [&>div>div]:table-fixed px-3">
    <div class="flex flex-col gap-2 pb-3 size-full">
      {#if filteredRecords}
        {#each filteredRecords as item (item.id)}
          <SidebarItem {item} />
        {/each}
      {:else}
        <span>List is empty</span>
      {/if}
    </div>
  </ScrollArea>
</div>

// new-tauri-app/src/widgets/sidebar/sidebar.tsx
import { createDexieArrayQuery } from 'solid-dexie'
import { Icon } from 'solid-heroicons'
import { ellipsisHorizontal, plus } from 'solid-heroicons/outline'
import { type Component, For } from 'solid-js'

import BrowserFileButton from '~/features/browse-file/browse-file'
import { Logo } from '~/features/logo'
import { db, ImageRecord } from '~/shared/db'
import { searchString } from '~/shared/store/search-store'
import { Button } from '~/shared/ui/button'

import SidebarItem from './sidebar-item'
import SidebarSearch from './sidebar-search'

const SideBar: Component = () => {
  const records = createDexieArrayQuery(() =>
    db.records.toArray()
  ) as ImageRecord[]
  return (
    <div class="flex size-full flex-col gap-2 px-3">
      <div class="flex h-12 w-full shrink-0 items-center justify-between border-b">
        <Logo />
        <div class="flex items-center gap-1">
          <BrowserFileButton size="icon" variant="ghost" class="size-8">
            <Icon path={plus} class="size-5" />
          </BrowserFileButton>
          <Button size="icon" variant="ghost" class="size-8">
            <Icon path={ellipsisHorizontal} class="size-6" />
          </Button>
        </div>
      </div>
      <div class="my-1 flex h-10 w-full items-center">
        <SidebarSearch />
      </div>
      <ul class="flex size-full flex-col gap-2 overflow-y-auto overflow-x-hidden">
        <For
          each={records.filter((x: ImageRecord) => {
            const searchStr = searchString().toLowerCase()
            return !searchStr || x.name.toLowerCase().includes(searchStr)
          })}
        >
          {(item) => <SidebarItem item={item} />}
        </For>
      </ul>
    </div>
  )
}

export default SideBar
