// apps/desktop/src/widgets/sidebar/sidebar-search.svelte
<script lang="ts">
  import { shortcut } from '@svelte-put/shortcut'
  import SearchIcon from 'lucide-svelte/icons/search'

  import { searchString } from '@/shared/stores/search-store'

  let inputRef: HTMLInputElement | undefined
  let searchInputValue = ''

  const handleK = () => inputRef?.focus()

  searchString.subscribe((value: string) => (searchInputValue = value))
</script>

<div
  class="flex h-8 w-full items-center gap-2 rounded-md border bg-secondary/[.7] px-2"
>
  <SearchIcon class="size-4 shrink-0 text-muted-foreground" />
  <input
    bind:this={inputRef}
    bind:value={searchInputValue}
    on:input={() => {
      searchString.set(searchInputValue)
    }}
    name="sidebar-search"
    class="w-full bg-transparent pt-px text-sm placeholder:text-sm placeholder:font-light placeholder:text-secondary-foreground focus:outline-none"
    placeholder="Search"
  />
  <div class="ms-auto inline-flex shrink-0 gap-0.5 font-light">
    <kbd
      class="flex size-6 items-center justify-center rounded-md border bg-background pt-px text-sm transition-colors hover:cursor-pointer hover:bg-secondary/80"
    >
      ⌘
    </kbd>
    <kbd
      class="flex size-6 items-center justify-center rounded-md border bg-background text-sm transition-colors hover:cursor-pointer hover:bg-secondary/80"
    >
      K
    </kbd>
  </div>
</div>

<svelte:window
  use:shortcut={{
    trigger: {
      key: 'k',
      modifier: ['ctrl', 'meta'],
      callback: handleK,
    },
  }}
/>

// new-tauri-app/src/widgets/sidebar/sidebar-search.tsx
import { useKeyDownSequence } from '@solid-primitives/keyboard'
import { Icon } from 'solid-heroicons'
import { magnifyingGlass } from 'solid-heroicons/outline'
import { type Component, createEffect } from 'solid-js'

import { searchString, setSearchString } from '~/shared/store/search-store'

const SidebarSearch: Component = () => {
  let inputRef: HTMLInputElement | undefined

  const sequence = useKeyDownSequence()

  createEffect(() => {
    const currentSequence = sequence()
    const lastKeys = currentSequence[currentSequence.length - 1] || []
    if (lastKeys.length == 0 || !isSuquencePressed(lastKeys)) return
    inputRef?.focus()
  })

  const isSuquencePressed = (keys: string[]) =>
    keys.includes('K') && (keys.includes('META') || keys.includes('CONTROL'))

  return (
    <div class="flex h-8 w-full items-center gap-2 rounded-md border bg-secondary/[.7] px-2">
      <Icon path={magnifyingGlass} class="size-4 shrink-0 pt-[2px]" />
      <input
        ref={inputRef}
        value={searchString()}
        onInput={(e) => setSearchString(e.target.value)}
        class="w-full bg-inherit pt-px text-sm placeholder:text-sm placeholder:font-light placeholder:text-secondary-foreground focus:outline-none"
        placeholder="Search"
      />
      <div class="ms-auto inline-flex shrink-0 gap-0.5 font-light">
        <kbd class="flex size-6 items-center justify-center rounded-md border bg-background transition-colors hover:cursor-pointer hover:bg-secondary/80">
          ⌘
        </kbd>
        <kbd class="flex size-6 items-center justify-center rounded-md border bg-background text-sm transition-colors hover:cursor-pointer hover:bg-secondary/80">
          K
        </kbd>
      </div>
    </div>
  )
}

export default SidebarSearch
