// new-tauri-app/src/pages/main/main-page.tsx
import { Component, Show } from 'solid-js'

import { selectedRecord } from '~/shared/store'
import { Tabs, TabsContent } from '~/shared/ui/tabs'
import { ImageViewer } from '~/widgets/image-viewer'
import { SideBar } from '~/widgets/sidebar'
import TextEditor from '~/widgets/text-editor/text-editor'

import UnselectedRecordBlock from './unselected-record-block'
import WorkspaceHeader from './workspace-header'

const MainPage: Component = () => {
  return (
    <div class="grid size-full grid-cols-[15rem_1fr] divide-x border-t">
      <SideBar />
      <div class="size-full overflow-hidden bg-secondary">
        <Show when={!selectedRecord()}>
          <div class="flex size-full items-center justify-center">
            <UnselectedRecordBlock />
          </div>
        </Show>
        <Show when={selectedRecord()}>
          {(record) => (
            <Tabs defaultValue="account" class="flex size-full flex-col">
              <WorkspaceHeader />
              <TabsContent value="image" class="size-full">
                <ImageViewer
                  imagePath={record().path}
                  blocks={record().blocks}
                />
              </TabsContent>
              <TabsContent value="text" class="size-full px-2.5">
                <TextEditor text={record().text} />
              </TabsContent>
            </Tabs>
          )}
        </Show>
      </div>
    </div>
  )
}

export default MainPage

// tauri-svelte-app/src/pages/main/main-page.svelte
<script lang="ts">
  import * as Tabs from '@/shared/ui/tabs'
  import { Sidebar } from '@/widgets/sidebar'
  import { selectedRecord } from '@/shared/stores/record-store'
  import UnselectedRecordBlock from './unselected-record-block.svelte'
  import WorkspaceHeader from './workspace-header.svelte'
  import { ImageViewer } from "@/widgets/image-viewer";
  import type {TextBox} from "@/shared/db";

  let isSelected = false
  let currentRecordText = ''
  let imagePath = ''
  let textBoxes: TextBox[] = []

  selectedRecord.subscribe((value) => {
    isSelected = !!value
    currentRecordText = value?.text ?? ''
    imagePath = value?.path ?? ''
    textBoxes = value?.blocks ?? []
  })
</script>

<div class="grid size-full grid-cols-[15rem_1fr] divide-x border-t">
  <Sidebar />
  <div class="size-full overflow-hidden bg-secondary dark:bg-secondary/[.1]">
    {#if isSelected}
      <Tabs.Root class="size-full">
        <WorkspaceHeader />
        <Tabs.Content value="text" class="size-full mt-0">
          <textarea
            value={currentRecordText}
            placeholder="Recognized text..."
            class="size-full px-3 py-2 resize-none bg-transparent focus:outline-none"
          />
        </Tabs.Content>
        <Tabs.Content value="image" class="size-full mt-0">
          <ImageViewer {imagePath} {textBoxes} className="size-full" />
        </Tabs.Content>
      </Tabs.Root>
    {:else}
      <div class="size-full flex items-center justify-center">
        <UnselectedRecordBlock />
      </div>
    {/if}
  </div>
</div>
