// apps/desktop/src/pages/main/workspace-header.svelte
<script lang="ts">
  import { Button } from '@repo/ui/button'
  import * as Tabs from '@repo/ui/tabs'
  import ArrowLeftIcon from 'lucide-svelte/icons/arrow-left'
  import TrashIcon from 'lucide-svelte/icons/trash'
  import { get } from 'svelte/store'
  import { toast } from 'svelte-sonner'

  import { deleteImageRecord } from '@/entities/image-record'
  import { selectedRecord } from '@/shared/stores/record-store'

  const deleteSelectedRecord = async () => {
    try {
      const currentRecord = get(selectedRecord)
      if (!currentRecord) return
      await deleteImageRecord(currentRecord.id)
      selectedRecord.set(undefined)
    } catch (ex) {
      const msg =
        ex instanceof Error ? ex.message : 'Error when deleting a record'
      toast.error(msg)
    }
  }
</script>

<div
  class="flex h-12 w-full shrink-0 items-center justify-between gap-2 border-b bg-background px-4"
>
  <Button
    on:click={() => {
      selectedRecord.set(undefined)
    }}
    variant="ghost"
    size="icon"
    class="size-8"
  >
    <ArrowLeftIcon class="size-4" />
  </Button>
  <Tabs.List class="grid h-8 w-32 grid-cols-2 p-1">
    <Tabs.Trigger value="image" class="py-1 text-xs font-normal">
      Image
    </Tabs.Trigger>
    <Tabs.Trigger value="text" class="py-1 text-xs font-normal">
      Text
    </Tabs.Trigger>
  </Tabs.List>
  <Button size="icon" class="size-8" on:click={() => deleteSelectedRecord()}>
    <TrashIcon class="size-4" />
  </Button>
</div>

// new-tauri-app/src/pages/main/workspace-header.tsx
import { Icon } from 'solid-heroicons'
import { arrowLeft, trash } from 'solid-heroicons/outline'
import { type Component } from 'solid-js'

import { db } from '~/shared/db'
import { selectedRecord, setSelectedRecord } from '~/shared/store'
import { Button } from '~/shared/ui/button'
import { TabsList, TabsTrigger } from '~/shared/ui/tabs'

const WorkspaceHeader: Component = () => {
  const deleteSelectedRecord = async () => {
    const curretnRecord = selectedRecord()
    if (!curretnRecord) return
    await db.records.delete(curretnRecord.id)
    setSelectedRecord(undefined)
  }
  return (
    <div class="flex h-12 w-full shrink-0 items-center justify-between gap-2 border-b bg-background px-4">
      <Button
        onClick={() => {
          setSelectedRecord(undefined)
        }}
        variant="ghost"
        size="icon"
        class="size-8"
      >
        <Icon path={arrowLeft} class="size-4" />
      </Button>
      <TabsList class="grid h-8 w-32 grid-cols-2 p-1">
        <TabsTrigger value="image" class="py-1 text-xs font-normal">
          Image
        </TabsTrigger>
        <TabsTrigger value="text" class="py-1 text-xs font-normal">
          Text
        </TabsTrigger>
      </TabsList>
      <Button
        size="icon"
        class="size-8"
        onClick={() => void deleteSelectedRecord()}
      >
        <Icon path={trash} class="size-4" />
      </Button>
    </div>
  )
}

export default WorkspaceHeader
